// <auto-generated />
namespace EoraMarketplace.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class createDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createDate));
        
        string IMigrationMetadata.Id
        {
            get { return "201609151434005_createDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
